# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20170326_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='request',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
